# Generated by Django 5.0.4 on 2024-04-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_project_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_id',
            field=models.CharField(default=1, max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
