# Generated by Django 5.0.4 on 2024-04-23 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
