# Generated by Django 5.0.4 on 2024-04-29 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0011_delete_userprofile"),
        ("users", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="users.customer",
            ),
        ),
    ]
